// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoTflzvOULv9nABO_IXGIik1PRq_8ez_U',
    appId: '1:621961382107:web:262f1dbf15f576e45fa4fe',
    messagingSenderId: '621961382107',
    projectId: 'mathdz-5c8d2',
    authDomain: 'mathdz-5c8d2.firebaseapp.com',
    storageBucket: 'mathdz-5c8d2.firebasestorage.app',
    measurementId: 'G-EN8R6LFDL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RSBy2Unm4mqQhPqxZdGY0paqv9aQsHM',
    appId: '1:621961382107:android:1a69232da4186fdc5fa4fe',
    messagingSenderId: '621961382107',
    projectId: 'mathdz-5c8d2',
    storageBucket: 'mathdz-5c8d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKqFm4sekp45OLtRe3NCEbOd4Cu6EiTU',
    appId: '1:621961382107:ios:959895ae57858c2d5fa4fe',
    messagingSenderId: '621961382107',
    projectId: 'mathdz-5c8d2',
    storageBucket: 'mathdz-5c8d2.firebasestorage.app',
    androidClientId: '621961382107-1r0820krdmhclmp2upsn6loearago8pq.apps.googleusercontent.com',
    iosClientId: '621961382107-nh859kom5mcqkd2t0e48lq5mg4gcea57.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathdz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKqFm4sekp45OLtRe3NCEbOd4Cu6EiTU',
    appId: '1:621961382107:ios:959895ae57858c2d5fa4fe',
    messagingSenderId: '621961382107',
    projectId: 'mathdz-5c8d2',
    storageBucket: 'mathdz-5c8d2.firebasestorage.app',
    androidClientId: '621961382107-1r0820krdmhclmp2upsn6loearago8pq.apps.googleusercontent.com',
    iosClientId: '621961382107-nh859kom5mcqkd2t0e48lq5mg4gcea57.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathdz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoTflzvOULv9nABO_IXGIik1PRq_8ez_U',
    appId: '1:621961382107:web:066ab8b0ec01eb1b5fa4fe',
    messagingSenderId: '621961382107',
    projectId: 'mathdz-5c8d2',
    authDomain: 'mathdz-5c8d2.firebaseapp.com',
    storageBucket: 'mathdz-5c8d2.firebasestorage.app',
    measurementId: 'G-1QR4QR11Q5',
  );

}